version: '2'

services:

  proxy:
    image: nginx:1.18.0-alpine
    ports:
    - "80:80"
    volumes:
    - ./code:/code
    - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
    - front
    depends_on:
    - web
    - adminer

  web:
    image: php-kase:v1
    build: php
    volumes:
    - ./code:/code
    networks:
    - front
    - back

  sender:
    image: php-kase:v1
    command: php /code/sender.php
    volumes:
    - ./code:/code
    networks:
    - back
    restart: on-failure
    depends_on:
      composer:
        condition: service_started
      queue:
        condition: service_healthy

  receiver:
    image: php-kase:v1
    command: php /code/receiver.php
    volumes:
    - ./code:/code
    scale: 3
    networks:
    - back
    restart: on-failure
    depends_on:
      composer:
        condition: service_started
      queue:
        condition: service_healthy

  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: xyz
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: xyz
    volumes:
    - ./seed:/docker-entrypoint-initdb.d
    - data:/var/lib/mysql
    networks:
    - back

  queue:
    image: rabbitmq-kase:v1
    build: rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
    - queue:/var/lib/rabbitmq
    networks:
    - front
    - back

  adminer:
    image: adminer:4.8.0
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
    - front
    - back

  composer:
    image: php-kase:v1
    volumes:
      - ./code:/app
    command: composer install --ignore-platform-reqs

networks:
  front:
  back:

volumes:
  data:
  queue:
